### ISSUE TITLE
message board 無法新增評論

### ISSUE THREAD

**Issue by AsheAnn** [wwwweiJ/Demo#120]
![image](https://user-images.githubusercontent.com/50226428/170695645-18b37053-8ae3-498a-86ea-991ded86e7fe.png)

**Comment by AsheAnn** [comment]
https://github.com/TurboCamp/TurboCamp/issues/101#issue-1246155079
兩個issues合併一起修改

**Comment by Kris3131** [comment]
無法新增 comment   可以問一下瑋玨之後的model是如何調整
@wwwwweiJ

**Comment by wwwwweiJ** [comment]
這個我解決後跟聊天室同分之一起推 @AsheAnn
