### ISSUE TITLE
顯示個人大頭貼在navbar右方

### ISSUE THREAD

**Issue by wwwwweiJ** [wwwweiJ/Demo#82]
![截圖 2022-05-20 20 42 52](https://user-images.githubusercontent.com/100756925/169530436-0aa0a760-3d1b-41da-b32c-20fa52480c22.png)
貼

-顯示個人頭貼在在navbar右方並直接連結到會員資料更新頁面
-將sidebar的setting拿掉

**Comment by AsheAnn** [comment]
![image](https://user-images.githubusercontent.com/50226428/169650470-5a982cdc-9869-4fd6-9284-4b8b23cabaf3.png)
- 個人頭貼放在左下角
